import {
  IconAlertTriangle,
  IconArrowRight,
  IconBrandGithub,
  IconBrandTwitter,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClipboardList,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMap,
  IconMessageCircle,
  IconMoon,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconSettings,
  IconShoppingBag,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserCog,
  IconUserEdit,
  IconUsers,
  IconUsersGroup,
  IconUserX,
  IconX,
  IconBellCheck
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  bell:IconBellCheck,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  plots: IconMap,
  requests: IconClipboardList,
  clientManagement: IconUsers,
  account: IconUserCog,
  manager: IconUserCog,
  feedback: IconMessageCircle,
  allUsers: IconUsersGroup
};
